
[mechanics]
	#If this is true, players will be able to see their progress towards the next rung. This is server side and will only be active in multiplayer if the server/Lan host has it activated.
	echeladderProgress = true
	#The highest rung you can get before entering medium. Note that the first rung is indexed as 0, the second as 1 and so on.
	#Range: 0 ~ 49
	preEntryRungLimit = 6
	#If true, players will respawn with full health, rung bonuses included. If false, health will be left alone (typically meaning that you respawn with 10 hearts)
	rungHealthOnRespawn = true
	#If this is true, players will gain certain potion effects once they reach a certain rung based on their aspect.
	aspectEffects = true
	#Enable this to let players select their own title. They will however not be able to select the Lord or Muse as class.
	playerSelectedTitle = true
	#Determines how quickly consort dialogue and store stocks are renewed.
	#Range: 0 ~ 1000
	dialogueRenewalSpeed = 2
	#Determines how many seconds it takes for the lotus blossom to regrow after the opening process has started.
	#Range: > 30
	lotusRestorationTime = 600
	hardMode = false

[sylladex]
	#When sylladices may drop items and cards at the same time, this option determines if items should be dropped inside of cards or items and cards as different stacks.
	dropItemsInCards = true
	#The initial amount of captchalogue cards in your sylladex.
	#Range: > 0
	initialModusSize = 5
	#The max size on a modus. Ignored if the value is 0.
	#Range: > 0
	modusMaxSize = 0
	#Determines which items from the modus that are dropped on death. "items": Only the items are dropped. "cards_and_items": Both items and cards are dropped. (So that you have at most initial_modus_size amount of cards) "all": Everything is dropped, even the modus.
	#Allowed Values: ITEMS, CARDS_AND_ITEMS, ALL
	dropMode = "CARDS_AND_ITEMS"
	#This determines if auto-balance should be forced. 'both' if the player should choose, 'on' if forced at on, and 'off' if forced at off.
	#Allowed Values: BOTH, ON, OFF
	treeModusSetting = "BOTH"
	#This determines if hashmap chat ejection should be forced. 'both' if the player should choose, 'on' if forced at on, and 'off' if forced at off.
	#Allowed Values: BOTH, ON, OFF
	hashmapModusSetting = "BOTH"

[computer]
	#True if computers should only be able to be used by the owner.
	privateComputers = true
	#Whenever all sburb connections should be put into a single session or not.
	globalSession = false
	#If enabled, will during certain moments perform a check on all connections and computers that are in use. Recommended to turn off if there is a need to improve performance, however skaianet-related bugs might appear when done so.
	skaianetCheck = true
	#Determines who's allowed to access the data checker. "none": No one is allowed. "ops": only those with a command permission of level 2 or more may access the data ckecker. (for single player, that would be if cheats are turned on) "gamemode": Only players with the creative or spectator gamemode may view the data checker. "ops_or_gamemode": Both ops and players in creative or spectator mode may view the data checker. "anyone": No access restrictions are used.
	#Allowed Values: NONE, OPS, GAMEMODE, OPS_OR_GAMEMODE, ANYONE
	dataCheckerPermission = "OPS_OR_GAMEMODE"

[editMode]
	#If this is true, grist change messages will appear.
	showGristChanges = true
	#Enable this and players will get a (full) grist refund from breaking blocks in editmode.
	gristRefund = false
	#Determines if a card with a captcha card punched on it should be added to the deploy list.
	deployCard = false
	#Determines if the small portable machines should be included in the deploy list.
	portableMachines = false
	#Setting this to true replaces editmode with the old Give Items button.
	giveItems = false
	#A number that determines how far away from the computer an editmode player may be before entry.
	#Range: > 1
	overworldEditRange = 15
	#A number that determines how far away from the center of the brought land that an editmode player may be after entry.
	#Range: > 1
	landEditRange = 30

[machines]
	#Disable Grist Widget
	disableGristWidget = false
	#The number of stacks that can be alchemized at the same time with the alchemiter.
	#Range: 0 ~ 999
	alchemiterMaxStacks = 16
	#How often puzzle/redstone related blocks such as the remote observer tick.
	#Range: 2 ~ 10
	puzzleBlockTickRate = 6
	#If enabled, the regular cruxtruder will require raw cruxite to function, which is inserted through the pipe.
	cruxtruderIntake = true
	#A list of worlds that you cannot travel to or from using transportalizers.
	forbiddenWorldsTpz = []
	#A list of dimension types that you cannot travel to or from using transportalizers.
	forbiddenDimensionTypesTpz = []

[entry]
	#Disable this to prevent craters from people entering the medium.
	entryCrater = true
	#Adapt the transferred height to make the top non-air block to be placed at y:120. Makes entry take slightly longer.
	adaptEntryBlockHeight = true
	#If this is true, players may only use an artifact once, even if they end up in the overworld again.
	stopSecondEntry = false
	#If this is true, players need to have a computer nearby to Enter
	needComputer = false
	#Radius of the land brought into the medium.
	#Range: > 0
	artifactRange = 30

[medium]
	#Lets gates be destroyed by explosions. Turning this off will make gates use the same explosion resistance as bedrock.
	canBreakGates = true
	#Right now, the giclops pathfinding is currently causing huge amounts of lag due to their size. This option is a short-term solution that if true will disable giclops spawning and remove all existing giclopes.
	disableGiclops = true
	#Determines if imps will spawn naturally. Note that this does not affect other spawning methods or any imps that has already spawned.
	naturalImpSpawn = true
	#Determines if ogres will spawn naturally. Note that this does not affect other spawning methods or any ogres that has already spawned.
	naturalOgreSpawn = true
	#Determines if basilisks will spawn naturally. Note that this does not affect other spawning methods or any basilisks that has already spawned.
	naturalBasiliskSpawn = true
	#Determines if liches will spawn naturally. Note that this does not affect other spawning methods or any liches that has already spawned.
	naturalLichSpawn = true
	#Set this to true to allow so-called 'secondary connections' to be created.
	secondaryConnections = true

